spring:
  application:
    name: spring-ai-rag
# api key
  ai:
    retry:
      backoff:
        max-interval: 15
        initial-interval: 1
      max-attempts: 2
    mistralai:
      api-key: ${MISTRAL_API_KEY}
      embedding:
        options:
          model: mistral-embed # default and only model supported by mistral-ai for now, while for openAI there are alternate models available as well
    vectorstore:
      milvus:
        client:
          host: "localhost"
          port: 19530
          username: "root"
          password: "milvus"
        databaseName: "default"
        collectionName: "vector_store"
        embeddingDimension: 1536
        indexType: IVF_FLAT
        metricType: COSINE


server:
  port: 8090


ai:
  app:
    vectorStoreDir: /tmp/vector-store.json
    document2load:
      - classpath:/towvehicles.txt
      # Sportsman 212 - Weight 3,458 lbs
      - https://yamahaoutboards.com/outboards/350-150-hp/in-line-4/f150-(i4)/pb_spt_open_212_f150xb_9-10-2020-occ
      # Sportsman 232 - Weight 5,001  lbs
      - https://yamahaoutboards.com/outboards/350-150-hp/v6-4-2l/f300-(4-2l)/pb_spt_open-232_f300xsb2_6-29-2023_occ
      # Sportsman 322 - Weight 12,469 lbs
      - https://yamahaoutboards.com/outboards/xto-offshore/v8-5-6l/xf425/pb_spt_open-322_tw_lxf425usb2_8-26-2021_occ
      # Scout 380 LXF - Weight 19,443 lbs
      - https://yamahaoutboards.com/outboards/xto-offshore/v8-5-6l/xf425/pb_sct_380lxf_tr_xf425_8-30-2018_occ